sources:
  - name: LogicaHealth Sandbox v3
    handler:
      fhir:
        endpoint: https://api.logicahealth.org/PatientCloud10STU3/open

additionalTypeDefs: |
  type TinyMedicationResponse {
    MedicationName: String 
    Instructions: String
    Fields(fields: [String]): JSON
  }
  type PeriodStat {
    AVGMeanValue: Float
    Date: String
  }
  type AllTimeStat {
    BestValue: Float
    EIGHTYPCBestValue: Float
    AVGMeanValue: Float
  }
  type TinyPeakFlowResponse {
    statsForPeriod: [PeriodStat]
    statsAllTime: AllTimeStat
  }
  extend type Query {
    TinyMedicationRequest(PatientID: String!, dates: String): [TinyMedicationResponse]
    TinyPeakFlowStats(PatientID: String!, dates: String): TinyPeakFlowResponse
  }
additionalResolvers:
  - ./src/tinyMedicationRequest.js
  - ./src/tinyPeakFlowStats.js

serve:
  exampleQuery: ./example-queries/*.graphql
  port: ${PORT?}
  cors:
    origin:
      - "*"
    allowedHeaders:
      - "Origin"
      - "Content-Type"
      - "Authorization"
      - "Partner-Company"
      - "X-Requested-With"
    exposedHeaders:
      - "access-control-allow-headers"
      - "access-control-allow-methods"
      - "access-control-allow-origin"
      - "content-type"
